// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PunchApiProject.Data;

#nullable disable

namespace PunchApiProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250701063244_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("PunchApiProject.Models.PunchRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PunchInTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PunchOutTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PunchRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
