//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 03-02-2026 16:16:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.Extensions.Configuration;

namespace PunchInOutContext
{

    [DatabaseAttribute(Name = "PunchInOut")]
    [ProviderAttribute(typeof(Devart.Data.SqlServer.Linq.Provider.SqlDataProvider))]
    public partial class PunchInOutDataContext : Devart.Data.Linq.DataContext
    {
        public static CompiledQueryCache compiledQueryCache = CompiledQueryCache.RegisterDataContext(typeof(PunchInOutDataContext));
        private static MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions
    
        partial void OnCreated();
        partial void OnSubmitError(Devart.Data.Linq.SubmitErrorEventArgs args);
        partial void InsertEFMigrationsHistory(EFMigrationsHistory instance);
        partial void UpdateEFMigrationsHistory(EFMigrationsHistory instance);
        partial void DeleteEFMigrationsHistory(EFMigrationsHistory instance);
        partial void InsertEMP(EMP instance);
        partial void UpdateEMP(EMP instance);
        partial void DeleteEMP(EMP instance);
        partial void InsertEmployee(Employee instance);
        partial void UpdateEmployee(Employee instance);
        partial void DeleteEmployee(Employee instance);
        partial void InsertEmployeeActivity(EmployeeActivity instance);
        partial void UpdateEmployeeActivity(EmployeeActivity instance);
        partial void DeleteEmployeeActivity(EmployeeActivity instance);
        partial void InsertEmployeeContact(EmployeeContact instance);
        partial void UpdateEmployeeContact(EmployeeContact instance);
        partial void DeleteEmployeeContact(EmployeeContact instance);
        partial void InsertEmployee1(Employee1 instance);
        partial void UpdateEmployee1(Employee1 instance);
        partial void DeleteEmployee1(Employee1 instance);
        partial void InsertPunchRecord(PunchRecord instance);
        partial void UpdatePunchRecord(PunchRecord instance);
        partial void DeletePunchRecord(PunchRecord instance);
        partial void InsertManager(Manager instance);
        partial void UpdateManager(Manager instance);
        partial void DeleteManager(Manager instance);

        #endregion

        public PunchInOutDataContext() :
        base(GetConnectionString("PunchInOutDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        public PunchInOutDataContext(MappingSource mappingSource) :
        base(GetConnectionString("PunchInOutDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        private static string GetConnectionString(string connectionStringName)
        {
            var configurationBuilder = new ConfigurationBuilder().AddJsonFile("appsettings.json", optional: true, reloadOnChange: false);
            var configuration = configurationBuilder.Build();
            return configuration.GetConnectionString(connectionStringName);
        }

        public PunchInOutDataContext(string connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public PunchInOutDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public PunchInOutDataContext(string connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public PunchInOutDataContext(System.Data.IDbConnection connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public Devart.Data.Linq.Table<EFMigrationsHistory> EFMigrationsHistories
        {
            get
            {
                return this.GetTable<EFMigrationsHistory>();
            }
        }

        public Devart.Data.Linq.Table<EMP> EMPs
        {
            get
            {
                return this.GetTable<EMP>();
            }
        }

        public Devart.Data.Linq.Table<Employee> Employees
        {
            get
            {
                return this.GetTable<Employee>();
            }
        }

        public Devart.Data.Linq.Table<EmployeeActivity> EmployeeActivities
        {
            get
            {
                return this.GetTable<EmployeeActivity>();
            }
        }

        public Devart.Data.Linq.Table<EmployeeContact> EmployeeContacts
        {
            get
            {
                return this.GetTable<EmployeeContact>();
            }
        }

        public Devart.Data.Linq.Table<Employee1> Employee1s
        {
            get
            {
                return this.GetTable<Employee1>();
            }
        }

        public Devart.Data.Linq.Table<PunchRecord> PunchRecords
        {
            get
            {
                return this.GetTable<PunchRecord>();
            }
        }

        public Devart.Data.Linq.Table<Manager> Managers
        {
            get
            {
                return this.GetTable<Manager>();
            }
        }
    }
}

namespace PunchInOutContext
{

    /// <summary>
    /// There are no comments for PunchInOutContext.EFMigrationsHistory in the schema.
    /// </summary>
    [Table(Name = @"dbo.[__EFMigrationsHistory]")]
    public partial class EFMigrationsHistory : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private string _MigrationId;

        private string _ProductVersion;
        #pragma warning restore 0649

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnMigrationIdChanging(string value);
        partial void OnMigrationIdChanged();
        partial void OnProductVersionChanging(string value);
        partial void OnProductVersionChanged();
        #endregion

        public EFMigrationsHistory()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for MigrationId in the schema.
        /// </summary>
        [Column(Storage = "_MigrationId", CanBeNull = false, DbType = "NVARCHAR(150) NOT NULL", IsPrimaryKey = true)]
        public string MigrationId
        {
            get
            {
                return this._MigrationId;
            }
            set
            {
                if (this._MigrationId != value)
                {
                    this.OnMigrationIdChanging(value);
                    this.SendPropertyChanging("MigrationId");
                    this._MigrationId = value;
                    this.SendPropertyChanged("MigrationId");
                    this.OnMigrationIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ProductVersion in the schema.
        /// </summary>
        [Column(Storage = "_ProductVersion", CanBeNull = false, DbType = "NVARCHAR(32) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string ProductVersion
        {
            get
            {
                return this._ProductVersion;
            }
            set
            {
                if (this._ProductVersion != value)
                {
                    this.OnProductVersionChanging(value);
                    this.SendPropertyChanging("ProductVersion");
                    this._ProductVersion = value;
                    this.SendPropertyChanged("ProductVersion");
                    this.OnProductVersionChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for PunchInOutContext.EMP in the schema.
    /// </summary>
    [Table(Name = @"dbo.EMP")]
    public partial class EMP : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _EMPID;

        private string _Gender;
        #pragma warning restore 0649

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnEMPIDChanging(int value);
        partial void OnEMPIDChanged();
        partial void OnGenderChanging(string value);
        partial void OnGenderChanged();
        #endregion

        public EMP()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for EMPID in the schema.
        /// </summary>
        [Column(Name = @"EMP_ID", Storage = "_EMPID", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT NOT NULL IDENTITY", IsDbGenerated = true, IsPrimaryKey = true)]
        public int EMPID
        {
            get
            {
                return this._EMPID;
            }
            set
            {
                if (this._EMPID != value)
                {
                    this.OnEMPIDChanging(value);
                    this.SendPropertyChanging("EMPID");
                    this._EMPID = value;
                    this.SendPropertyChanged("EMPID");
                    this.OnEMPIDChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Gender in the schema.
        /// </summary>
        [Column(Name = @"gender", Storage = "_Gender", CanBeNull = false, DbType = "VARCHAR(10) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                if (this._Gender != value)
                {
                    this.OnGenderChanging(value);
                    this.SendPropertyChanging("Gender");
                    this._Gender = value;
                    this.SendPropertyChanged("Gender");
                    this.OnGenderChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for PunchInOutContext.Employee in the schema.
    /// </summary>
    [Table(Name = @"dbo.Employee")]
    public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private string _EmpId;

        private int? _EmpName;

        private int? _EmpDept;

        private int? _Age;
        #pragma warning restore 0649

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnEmpIdChanging(string value);
        partial void OnEmpIdChanged();
        partial void OnEmpNameChanging(int? value);
        partial void OnEmpNameChanged();
        partial void OnEmpDeptChanging(int? value);
        partial void OnEmpDeptChanged();
        partial void OnAgeChanging(int? value);
        partial void OnAgeChanged();
        #endregion

        public Employee()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for EmpId in the schema.
        /// </summary>
        [Column(Name = @"Emp_id", Storage = "_EmpId", CanBeNull = false, DbType = "VARCHAR(1) NOT NULL", IsPrimaryKey = true)]
        public string EmpId
        {
            get
            {
                return this._EmpId;
            }
            set
            {
                if (this._EmpId != value)
                {
                    this.OnEmpIdChanging(value);
                    this.SendPropertyChanging("EmpId");
                    this._EmpId = value;
                    this.SendPropertyChanged("EmpId");
                    this.OnEmpIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EmpName in the schema.
        /// </summary>
        [Column(Name = @"Emp_name", Storage = "_EmpName", DbType = "INT", UpdateCheck = UpdateCheck.Never)]
        public int? EmpName
        {
            get
            {
                return this._EmpName;
            }
            set
            {
                if (this._EmpName != value)
                {
                    this.OnEmpNameChanging(value);
                    this.SendPropertyChanging("EmpName");
                    this._EmpName = value;
                    this.SendPropertyChanged("EmpName");
                    this.OnEmpNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EmpDept in the schema.
        /// </summary>
        [Column(Name = @"Emp_dept", Storage = "_EmpDept", DbType = "INT", UpdateCheck = UpdateCheck.Never)]
        public int? EmpDept
        {
            get
            {
                return this._EmpDept;
            }
            set
            {
                if (this._EmpDept != value)
                {
                    this.OnEmpDeptChanging(value);
                    this.SendPropertyChanging("EmpDept");
                    this._EmpDept = value;
                    this.SendPropertyChanged("EmpDept");
                    this.OnEmpDeptChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Age in the schema.
        /// </summary>
        [Column(Name = @"age", Storage = "_Age", DbType = "INT", UpdateCheck = UpdateCheck.Never)]
        public int? Age
        {
            get
            {
                return this._Age;
            }
            set
            {
                if (this._Age != value)
                {
                    this.OnAgeChanging(value);
                    this.SendPropertyChanging("Age");
                    this._Age = value;
                    this.SendPropertyChanged("Age");
                    this.OnAgeChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for PunchInOutContext.EmployeeActivity in the schema.
    /// </summary>
    [Table(Name = @"dbo.employee_activities")]
    public partial class EmployeeActivity : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _ActivityId;

        private int _EmployeeId;

        private System.DateTime _PunchInTime;

        private System.DateTime? _PunchOutTime;
        #pragma warning restore 0649

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnActivityIdChanging(int value);
        partial void OnActivityIdChanged();
        partial void OnEmployeeIdChanging(int value);
        partial void OnEmployeeIdChanged();
        partial void OnPunchInTimeChanging(System.DateTime value);
        partial void OnPunchInTimeChanged();
        partial void OnPunchOutTimeChanging(System.DateTime? value);
        partial void OnPunchOutTimeChanged();
        #endregion

        public EmployeeActivity()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ActivityId in the schema.
        /// </summary>
        [Column(Name = @"activity_id", Storage = "_ActivityId", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT NOT NULL IDENTITY", IsDbGenerated = true, IsPrimaryKey = true)]
        public int ActivityId
        {
            get
            {
                return this._ActivityId;
            }
            set
            {
                if (this._ActivityId != value)
                {
                    this.OnActivityIdChanging(value);
                    this.SendPropertyChanging("ActivityId");
                    this._ActivityId = value;
                    this.SendPropertyChanged("ActivityId");
                    this.OnActivityIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EmployeeId in the schema.
        /// </summary>
        [Column(Name = @"employee_id", Storage = "_EmployeeId", CanBeNull = false, DbType = "INT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int EmployeeId
        {
            get
            {
                return this._EmployeeId;
            }
            set
            {
                if (this._EmployeeId != value)
                {
                    this.OnEmployeeIdChanging(value);
                    this.SendPropertyChanging("EmployeeId");
                    this._EmployeeId = value;
                    this.SendPropertyChanged("EmployeeId");
                    this.OnEmployeeIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for PunchInTime in the schema.
        /// </summary>
        [Column(Name = @"punch_in_time", Storage = "_PunchInTime", CanBeNull = false, DbType = "DATETIME2 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime PunchInTime
        {
            get
            {
                return this._PunchInTime;
            }
            set
            {
                if (this._PunchInTime != value)
                {
                    this.OnPunchInTimeChanging(value);
                    this.SendPropertyChanging("PunchInTime");
                    this._PunchInTime = value;
                    this.SendPropertyChanged("PunchInTime");
                    this.OnPunchInTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for PunchOutTime in the schema.
        /// </summary>
        [Column(Name = @"punch_out_time", Storage = "_PunchOutTime", DbType = "DATETIME2", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime? PunchOutTime
        {
            get
            {
                return this._PunchOutTime;
            }
            set
            {
                if (this._PunchOutTime != value)
                {
                    this.OnPunchOutTimeChanging(value);
                    this.SendPropertyChanging("PunchOutTime");
                    this._PunchOutTime = value;
                    this.SendPropertyChanged("PunchOutTime");
                    this.OnPunchOutTimeChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for PunchInOutContext.EmployeeContact in the schema.
    /// </summary>
    [Table(Name = @"dbo.employee_contacts")]
    public partial class EmployeeContact : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _EmployeeContactId;

        private int _EmployeeId;

        private string _ContactNumber;
        #pragma warning restore 0649

        private EntityRef<Employee1> _Employee1;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnEmployeeContactIdChanging(int value);
        partial void OnEmployeeContactIdChanged();
        partial void OnEmployeeIdChanging(int value);
        partial void OnEmployeeIdChanged();
        partial void OnContactNumberChanging(string value);
        partial void OnContactNumberChanged();
        #endregion

        public EmployeeContact()
        {
            this._Employee1  = default(EntityRef<Employee1>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for EmployeeContactId in the schema.
        /// </summary>
        [Column(Storage = "_EmployeeContactId", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT NOT NULL IDENTITY", IsDbGenerated = true, IsPrimaryKey = true)]
        public int EmployeeContactId
        {
            get
            {
                return this._EmployeeContactId;
            }
            set
            {
                if (this._EmployeeContactId != value)
                {
                    this.OnEmployeeContactIdChanging(value);
                    this.SendPropertyChanging("EmployeeContactId");
                    this._EmployeeContactId = value;
                    this.SendPropertyChanged("EmployeeContactId");
                    this.OnEmployeeContactIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EmployeeId in the schema.
        /// </summary>
        [Column(Storage = "_EmployeeId", CanBeNull = false, DbType = "INT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int EmployeeId
        {
            get
            {
                return this._EmployeeId;
            }
            set
            {
                if (this._EmployeeId != value)
                {
                    if (this._Employee1.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnEmployeeIdChanging(value);
                    this.SendPropertyChanging("EmployeeId");
                    this._EmployeeId = value;
                    this.SendPropertyChanged("EmployeeId");
                    this.OnEmployeeIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ContactNumber in the schema.
        /// </summary>
        [Column(Storage = "_ContactNumber", CanBeNull = false, DbType = "NVARCHAR(MAX) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string ContactNumber
        {
            get
            {
                return this._ContactNumber;
            }
            set
            {
                if (this._ContactNumber != value)
                {
                    this.OnContactNumberChanging(value);
                    this.SendPropertyChanging("ContactNumber");
                    this._ContactNumber = value;
                    this.SendPropertyChanged("ContactNumber");
                    this.OnContactNumberChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Employee1 in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Employee1_EmployeeContact", Storage="_Employee1", ThisKey="EmployeeId", OtherKey="Id", IsForeignKey=true)]
        public Employee1 Employee1
        {
            get
            {
                return this._Employee1.Entity;
            }
            set
            {
                Employee1 previousValue = this._Employee1.Entity;
                if ((previousValue != value) || (this._Employee1.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging("Employee1");
                    if (previousValue != null)
                    {
                        this._Employee1.Entity = null;
                        previousValue.EmployeeContacts.Remove(this);
                    }
                    this._Employee1.Entity = value;
                    if (value != null)
                    {
                        this._EmployeeId = value.Id;
                        value.EmployeeContacts.Add(this);
                    }
                    else
                    {
                        this._EmployeeId = default(int);
                    }
                    this.SendPropertyChanged("Employee1");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for PunchInOutContext.Employee1 in the schema.
    /// </summary>
    [Table(Name = @"dbo.employees")]
    public partial class Employee1 : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private string _EmployeeId;

        private string _FirstName;

        private string _LastName;

        private string _Email;

        private string _Phone;

        private string _Department;

        private string _Position;

        private string _PasswordHash;

        private System.DateTime _JoinDate;

        private bool _IsActive;

        private System.DateTime _CreatedAt;

        private System.DateTime _UpdatedAt;
        #pragma warning restore 0649

        private EntitySet<EmployeeContact> _EmployeeContacts;

        private EntitySet<PunchRecord> _PunchRecords;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnEmployeeIdChanging(string value);
        partial void OnEmployeeIdChanged();
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        partial void OnDepartmentChanging(string value);
        partial void OnDepartmentChanged();
        partial void OnPositionChanging(string value);
        partial void OnPositionChanged();
        partial void OnPasswordHashChanging(string value);
        partial void OnPasswordHashChanged();
        partial void OnJoinDateChanging(System.DateTime value);
        partial void OnJoinDateChanged();
        partial void OnIsActiveChanging(bool value);
        partial void OnIsActiveChanged();
        partial void OnCreatedAtChanging(System.DateTime value);
        partial void OnCreatedAtChanged();
        partial void OnUpdatedAtChanging(System.DateTime value);
        partial void OnUpdatedAtChanged();
        #endregion

        public Employee1()
        {
            this._EmployeeContacts = new EntitySet<EmployeeContact>(new Action<EmployeeContact>(this.attach_EmployeeContacts), new Action<EmployeeContact>(this.detach_EmployeeContacts));
            this._PunchRecords = new EntitySet<PunchRecord>(new Action<PunchRecord>(this.attach_PunchRecords), new Action<PunchRecord>(this.detach_PunchRecords));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT NOT NULL IDENTITY", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EmployeeId in the schema.
        /// </summary>
        [Column(Name = @"employee_id", Storage = "_EmployeeId", CanBeNull = false, DbType = "NVARCHAR(50) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string EmployeeId
        {
            get
            {
                return this._EmployeeId;
            }
            set
            {
                if (this._EmployeeId != value)
                {
                    this.OnEmployeeIdChanging(value);
                    this.SendPropertyChanging("EmployeeId");
                    this._EmployeeId = value;
                    this.SendPropertyChanged("EmployeeId");
                    this.OnEmployeeIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for FirstName in the schema.
        /// </summary>
        [Column(Name = @"first_name", Storage = "_FirstName", CanBeNull = false, DbType = "NVARCHAR(100) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                if (this._FirstName != value)
                {
                    this.OnFirstNameChanging(value);
                    this.SendPropertyChanging("FirstName");
                    this._FirstName = value;
                    this.SendPropertyChanged("FirstName");
                    this.OnFirstNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for LastName in the schema.
        /// </summary>
        [Column(Name = @"last_name", Storage = "_LastName", CanBeNull = false, DbType = "NVARCHAR(100) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                if (this._LastName != value)
                {
                    this.OnLastNameChanging(value);
                    this.SendPropertyChanging("LastName");
                    this._LastName = value;
                    this.SendPropertyChanged("LastName");
                    this.OnLastNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Email in the schema.
        /// </summary>
        [Column(Name = @"email", Storage = "_Email", CanBeNull = false, DbType = "NVARCHAR(255) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                if (this._Email != value)
                {
                    this.OnEmailChanging(value);
                    this.SendPropertyChanging("Email");
                    this._Email = value;
                    this.SendPropertyChanged("Email");
                    this.OnEmailChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Phone in the schema.
        /// </summary>
        [Column(Name = @"phone", Storage = "_Phone", CanBeNull = false, DbType = "NVARCHAR(20) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                if (this._Phone != value)
                {
                    this.OnPhoneChanging(value);
                    this.SendPropertyChanging("Phone");
                    this._Phone = value;
                    this.SendPropertyChanged("Phone");
                    this.OnPhoneChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        [Column(Name = @"department", Storage = "_Department", CanBeNull = false, DbType = "NVARCHAR(100) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Department
        {
            get
            {
                return this._Department;
            }
            set
            {
                if (this._Department != value)
                {
                    this.OnDepartmentChanging(value);
                    this.SendPropertyChanging("Department");
                    this._Department = value;
                    this.SendPropertyChanged("Department");
                    this.OnDepartmentChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Position in the schema.
        /// </summary>
        [Column(Name = @"position", Storage = "_Position", CanBeNull = false, DbType = "NVARCHAR(100) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Position
        {
            get
            {
                return this._Position;
            }
            set
            {
                if (this._Position != value)
                {
                    this.OnPositionChanging(value);
                    this.SendPropertyChanging("Position");
                    this._Position = value;
                    this.SendPropertyChanged("Position");
                    this.OnPositionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for PasswordHash in the schema.
        /// </summary>
        [Column(Name = @"password_hash", Storage = "_PasswordHash", CanBeNull = false, DbType = "NVARCHAR(255) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string PasswordHash
        {
            get
            {
                return this._PasswordHash;
            }
            set
            {
                if (this._PasswordHash != value)
                {
                    this.OnPasswordHashChanging(value);
                    this.SendPropertyChanging("PasswordHash");
                    this._PasswordHash = value;
                    this.SendPropertyChanged("PasswordHash");
                    this.OnPasswordHashChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for JoinDate in the schema.
        /// </summary>
        [Column(Name = @"join_date", Storage = "_JoinDate", CanBeNull = false, DbType = "DATETIME2 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime JoinDate
        {
            get
            {
                return this._JoinDate;
            }
            set
            {
                if (this._JoinDate != value)
                {
                    this.OnJoinDateChanging(value);
                    this.SendPropertyChanging("JoinDate");
                    this._JoinDate = value;
                    this.SendPropertyChanged("JoinDate");
                    this.OnJoinDateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for IsActive in the schema.
        /// </summary>
        [Column(Name = @"is_active", Storage = "_IsActive", CanBeNull = false, DbType = "BIT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                if (this._IsActive != value)
                {
                    this.OnIsActiveChanging(value);
                    this.SendPropertyChanging("IsActive");
                    this._IsActive = value;
                    this.SendPropertyChanged("IsActive");
                    this.OnIsActiveChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for CreatedAt in the schema.
        /// </summary>
        [Column(Name = @"created_at", Storage = "_CreatedAt", CanBeNull = false, DbType = "DATETIME2 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime CreatedAt
        {
            get
            {
                return this._CreatedAt;
            }
            set
            {
                if (this._CreatedAt != value)
                {
                    this.OnCreatedAtChanging(value);
                    this.SendPropertyChanging("CreatedAt");
                    this._CreatedAt = value;
                    this.SendPropertyChanged("CreatedAt");
                    this.OnCreatedAtChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for UpdatedAt in the schema.
        /// </summary>
        [Column(Name = @"updated_at", Storage = "_UpdatedAt", CanBeNull = false, DbType = "DATETIME2 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime UpdatedAt
        {
            get
            {
                return this._UpdatedAt;
            }
            set
            {
                if (this._UpdatedAt != value)
                {
                    this.OnUpdatedAtChanging(value);
                    this.SendPropertyChanging("UpdatedAt");
                    this._UpdatedAt = value;
                    this.SendPropertyChanged("UpdatedAt");
                    this.OnUpdatedAtChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EmployeeContacts in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Employee1_EmployeeContact", Storage="_EmployeeContacts", ThisKey="Id", OtherKey="EmployeeId", DeleteRule="CASCADE")]
        public EntitySet<EmployeeContact> EmployeeContacts
        {
            get
            {
                return this._EmployeeContacts;
            }
            set
            {
                this._EmployeeContacts.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for PunchRecords in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Employee1_PunchRecord", Storage="_PunchRecords", ThisKey="Id", OtherKey="EmployeeId", DeleteRule="CASCADE")]
        public EntitySet<PunchRecord> PunchRecords
        {
            get
            {
                return this._PunchRecords;
            }
            set
            {
                this._PunchRecords.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_EmployeeContacts(EmployeeContact entity)
        {
            this.SendPropertyChanging("EmployeeContacts");
            entity.Employee1 = this;
        }
    
        private void detach_EmployeeContacts(EmployeeContact entity)
        {
            this.SendPropertyChanging("EmployeeContacts");
            entity.Employee1 = null;
        }

        private void attach_PunchRecords(PunchRecord entity)
        {
            this.SendPropertyChanging("PunchRecords");
            entity.Employee1 = this;
        }
    
        private void detach_PunchRecords(PunchRecord entity)
        {
            this.SendPropertyChanging("PunchRecords");
            entity.Employee1 = null;
        }
    }

    /// <summary>
    /// There are no comments for PunchInOutContext.PunchRecord in the schema.
    /// </summary>
    [Table(Name = @"dbo.punch_records")]
    public partial class PunchRecord : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private int _EmployeeId;

        private System.DateTime _ActionDateTime;

        private string _ActionType;
        #pragma warning restore 0649

        private EntityRef<Employee1> _Employee1;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnEmployeeIdChanging(int value);
        partial void OnEmployeeIdChanged();
        partial void OnActionDateTimeChanging(System.DateTime value);
        partial void OnActionDateTimeChanged();
        partial void OnActionTypeChanging(string value);
        partial void OnActionTypeChanged();
        #endregion

        public PunchRecord()
        {
            this._Employee1  = default(EntityRef<Employee1>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT NOT NULL IDENTITY", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for EmployeeId in the schema.
        /// </summary>
        [Column(Name = @"employee_id", Storage = "_EmployeeId", CanBeNull = false, DbType = "INT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int EmployeeId
        {
            get
            {
                return this._EmployeeId;
            }
            set
            {
                if (this._EmployeeId != value)
                {
                    if (this._Employee1.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnEmployeeIdChanging(value);
                    this.SendPropertyChanging("EmployeeId");
                    this._EmployeeId = value;
                    this.SendPropertyChanged("EmployeeId");
                    this.OnEmployeeIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ActionDateTime in the schema.
        /// </summary>
        [Column(Name = @"action_date_time", Storage = "_ActionDateTime", CanBeNull = false, DbType = "DATETIME2 NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime ActionDateTime
        {
            get
            {
                return this._ActionDateTime;
            }
            set
            {
                if (this._ActionDateTime != value)
                {
                    this.OnActionDateTimeChanging(value);
                    this.SendPropertyChanging("ActionDateTime");
                    this._ActionDateTime = value;
                    this.SendPropertyChanged("ActionDateTime");
                    this.OnActionDateTimeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ActionType in the schema.
        /// </summary>
        [Column(Name = @"action_type", Storage = "_ActionType", CanBeNull = false, DbType = "NVARCHAR(20) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string ActionType
        {
            get
            {
                return this._ActionType;
            }
            set
            {
                if (this._ActionType != value)
                {
                    this.OnActionTypeChanging(value);
                    this.SendPropertyChanging("ActionType");
                    this._ActionType = value;
                    this.SendPropertyChanged("ActionType");
                    this.OnActionTypeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Employee1 in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Employee1_PunchRecord", Storage="_Employee1", ThisKey="EmployeeId", OtherKey="Id", IsForeignKey=true)]
        public Employee1 Employee1
        {
            get
            {
                return this._Employee1.Entity;
            }
            set
            {
                Employee1 previousValue = this._Employee1.Entity;
                if ((previousValue != value) || (this._Employee1.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging("Employee1");
                    if (previousValue != null)
                    {
                        this._Employee1.Entity = null;
                        previousValue.PunchRecords.Remove(this);
                    }
                    this._Employee1.Entity = value;
                    if (value != null)
                    {
                        this._EmployeeId = value.Id;
                        value.PunchRecords.Add(this);
                    }
                    else
                    {
                        this._EmployeeId = default(int);
                    }
                    this.SendPropertyChanged("Employee1");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for PunchInOutContext.Manager in the schema.
    /// </summary>
    [Table(Name = @"dbo.[|Managers]")]
    public partial class Manager : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _MId;

        private string _ManagerName;

        private int _Salary;
        #pragma warning restore 0649

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnMIdChanging(int value);
        partial void OnMIdChanged();
        partial void OnManagerNameChanging(string value);
        partial void OnManagerNameChanged();
        partial void OnSalaryChanging(int value);
        partial void OnSalaryChanged();
        #endregion

        public Manager()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for MId in the schema.
        /// </summary>
        [Column(Storage = "_MId", CanBeNull = false, DbType = "INT NOT NULL", IsPrimaryKey = true)]
        public int MId
        {
            get
            {
                return this._MId;
            }
            set
            {
                if (this._MId != value)
                {
                    this.OnMIdChanging(value);
                    this.SendPropertyChanging("MId");
                    this._MId = value;
                    this.SendPropertyChanged("MId");
                    this.OnMIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ManagerName in the schema.
        /// </summary>
        [Column(Storage = "_ManagerName", CanBeNull = false, DbType = "NVARCHAR(MAX) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string ManagerName
        {
            get
            {
                return this._ManagerName;
            }
            set
            {
                if (this._ManagerName != value)
                {
                    this.OnManagerNameChanging(value);
                    this.SendPropertyChanging("ManagerName");
                    this._ManagerName = value;
                    this.SendPropertyChanged("ManagerName");
                    this.OnManagerNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Salary in the schema.
        /// </summary>
        [Column(Storage = "_Salary", CanBeNull = false, DbType = "INT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int Salary
        {
            get
            {
                return this._Salary;
            }
            set
            {
                if (this._Salary != value)
                {
                    this.OnSalaryChanging(value);
                    this.SendPropertyChanging("Salary");
                    this._Salary = value;
                    this.SendPropertyChanged("Salary");
                    this.OnSalaryChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
